name: genvar
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.83
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - logomaker=0.8
  - matplotlib=3.8.3
  - numpy=1.26.4
  - pandas=2.2.1
  - pip=24.0
  - python=3.12.3
  - pyfaidx=0.8.1.1
  - pyliftover=0.4
  - samtools=1.19.2
  - scipy=1.12.0
  - seaborn=0.13.2
  - statsmodels=0.14.1
  - pip:
      - cyvcf2==0.30.28
